name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAQWASBFOS6UMFABHS
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tekloon-test-stack
          template: workshop4.yaml
          no-fail-on-empty-changeset: "1"
